CREATE TABLE LECTURE
AS SELECT *
FROM dtaniar.LECTURE;

CREATE TABLE TUTOR
AS SELECT *
FROM dtaniar.TUTOR;

CREATE TABLE LAB
AS SELECT *
FROM dtaniar.LAB;

CREATE TABLE STUDENT_ENROLMENT
AS SELECT *
FROM dtaniar.STUDENT_ENROLMENT;

CREATE TABLE LAB_SIGNUP
AS SELECT *
FROM dtaniar.LAB_SIGNUP;

CREATE TABLE SUBJECT
AS SELECT *
FROM dtaniar.SUBJECT;
